made changes to child

diff --git a/.github/workflows/parent_workflow.yml b/.github/workflows/parent_workflow.yml
--- a/.github/workflows/parent_workflow.yml
+++ b/.github/workflows/parent_workflow.yml
@@ -1,33 +1,26 @@
-name: Build-Docker-Image-Parent
-
-on: [push]
-
+# .github/workflows/parent_workflow.yml
+name: Parent Workflow
+on:
+  push:
+    branches:
+      - main
 jobs:
-  build_docker_img:
+  trigger_child_workflow:
     runs-on: ubuntu-latest
     env:
-      TAG: python-api
-      DOCKER_USERNAME: ambarish6
-      DOCKER_PASSWORD: Ambi@9380
-      USER: ambarish6
-      VERSION: latest
-
+      GITHUB_TOKEN: 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
+      REPO_OWNER: ambarih
+      REPO_NAME: trivy_new
+      CHILD_WORKFLOW_ID: 95072086
     steps:
-    - name: Checkout
-      uses: actions/checkout@v1
-
-    - name: Login to Docker Hub
-      uses: docker/login-action@v1
-      with:
-        username: ${{ env.DOCKER_USERNAME }}
-        password: ${{ env.DOCKER_PASSWORD }}
-
-    - name: Build Docker image
-      id: build_image
-      run: docker build -t ${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }} .
-
-    - name: Trigger Child Workflow
-      if: ${{ always() }}
-      uses: ./.github/workflows/child_workflow.yml
-      with:
-        image_tag: ${{ steps.build_image.outputs.image_tag }}
+      - name: Trigger Child Workflow
+        uses: actions/checkout@v2
+      - name: Run Child Workflow
+        run: |
+          response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$CHILD_WORKFLOW_ID/dispatches -d '{"ref":"main"}' -w "%{http_code}")
+          if [[ $response != 2* ]]; then
+            echo "Failed to trigger child workflow"
+            exit 1
+          fi
+      - name: Example 
+        run: echo "This is an example step in the parent workflow"
