2

diff --git a/.github/workflows/parent_workflow.yml b/.github/workflows/parent_workflow.yml
--- a/.github/workflows/parent_workflow.yml
+++ b/.github/workflows/parent_workflow.yml
@@ -10,7 +10,7 @@ jobs:
       REPO_OWNER: ambarih
       REPO_NAME: trivy_new
       CHILD_WORKFLOW_ID: 95072086
-      token: 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
+      token: ${{ secrets.token }}
     steps:
       - name: Trigger Child Workflow
         uses: actions/checkout@v2
@@ -21,5 +21,19 @@ jobs:
             echo "Failed to trigger child workflow"
             exit 1
           fi
-      - name: Example 
-        run: echo "This is an example step in the parent workflow"
+      - name: Wait for Child Workflow Completion
+        id: wait_child_workflow
+        run: |
+          status="queued"
+          while [[ $status == "queued" || $status == "in_progress" ]]; do
+            sleep 30
+            status=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$CHILD_WORKFLOW_ID/runs/latest | jq -r .status)
+          done
+          if [[ $status != "completed" ]]; then
+            echo "Child workflow failed or canceled"
+            exit 1
+          fi
+      - name: Remaining Parent Workflow Steps
+        if: steps.wait_child_workflow.outputs.status == 'completed'
+        run: |
+          echo "Child workflow completed successfully, continuing with remaining steps"
